# Generated by Django 2.1.13 on 2019-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientesdeudores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codclideu', models.IntegerField(db_column='CodCliDeu')),
                ('rsocial', models.CharField(blank=True, db_column='Rsocial', max_length=100, null=True)),
                ('rut', models.CharField(blank=True, db_column='Rut', max_length=11, null=True)),
                ('email', models.CharField(blank=True, db_column='EMail', max_length=100, null=True)),
                ('codejec', models.IntegerField(blank=True, db_column='CodEjec', null=True)),
                ('cliente', models.BooleanField(db_column='Cliente')),
                ('deudor', models.BooleanField(db_column='Deudor')),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=50, null=True)),
                ('codcomuna', models.IntegerField(blank=True, db_column='CodComuna', null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcomuna', models.IntegerField(blank=True, db_column='CodComuna', null=True)),
                ('comuna', models.CharField(blank=True, db_column='Comuna', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejecutivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codemp', models.IntegerField(db_column='CodEmp')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellidopaterno', models.CharField(blank=True, db_column='ApellidoPaterno', max_length=100, null=True)),
                ('apellidomaterno', models.CharField(blank=True, db_column='ApellidoMaterno', max_length=100, null=True)),
                ('mailejecutivo', models.CharField(blank=True, db_column='MailEjecutivo', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=30, null=True)),
                ('nombreusuario', models.CharField(blank=True, db_column='NombreUsuario', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lineas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.IntegerField(blank=True, db_column='codCliente', null=True)),
                ('linea', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('vigente', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('vctolinea', models.DateField(blank=True, db_column='vctoLinea', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcliente', models.IntegerField(blank=True, db_column='CodCliente', null=True)),
                ('idoperencurso', models.IntegerField()),
                ('contrato', models.IntegerField(blank=True, db_column='Contrato', null=True)),
                ('fechaoper', models.DateTimeField(blank=True, db_column='FechaOper', null=True)),
                ('documento', models.CharField(blank=True, db_column='Documento', max_length=50, null=True)),
                ('cantdoctos', models.IntegerField(blank=True, db_column='CantDoctos', null=True)),
                ('valtotoper', models.DecimalField(blank=True, db_column='ValTotOper', decimal_places=4, max_digits=19, null=True)),
                ('anticipable', models.DecimalField(blank=True, db_column='Anticipable', decimal_places=4, max_digits=19, null=True)),
                ('porcentanticipejec', models.FloatField(blank=True, db_column='PorcentAnticipEjec', null=True)),
                ('totalgastos', models.DecimalField(blank=True, db_column='TotalGastos', decimal_places=4, max_digits=19, null=True)),
                ('comisionejec', models.DecimalField(blank=True, db_column='ComisionEjec', decimal_places=4, max_digits=19, null=True)),
                ('iva', models.DecimalField(blank=True, db_column='IVA', decimal_places=4, max_digits=19, null=True)),
                ('aplicaciones', models.IntegerField(blank=True, db_column='Aplicaciones', null=True)),
                ('montoagirar', models.DecimalField(blank=True, db_column='MontoaGirar', decimal_places=4, max_digits=19, null=True)),
                ('abonova', models.DecimalField(blank=True, db_column='AbonoVA', decimal_places=4, max_digits=19, null=True)),
            ],
        ),
    ]
